[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-docstring-description>=1.1.1",
  "hatch-fancy-pypi-readme",
  "hatch-vcs",
  "hatchling",
]

[project]
name = "fast-array-utils"
license = "MPL-2.0"
authors = [
  { name = "Philipp A.", email = "flying-sheep@web.de" },
]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
]
dynamic = [ "description", "readme", "version" ]
dependencies = [ "array-api-compat", "numpy>=2" ]
optional-dependencies.accel = [ "numba>=0.57" ]
optional-dependencies.dask = [ "dask>=2023.6.1" ]
optional-dependencies.full = [ "fast-array-utils[accel,dask,sparse]", "h5py", "zarr" ]
optional-dependencies.sparse = [ "scipy>=1.13" ]
optional-dependencies.testing = [ "packaging" ]
urls."Issue Tracker" = "https://github.com/scverse/fast-array-utils/issues"
urls."Source Code" = "https://github.com/scverse/fast-array-utils"
urls.Documentation = "https://icb-fast-array-utils.readthedocs-hosted.com/"
entry-points.pytest11.fast_array_utils = "testing.fast_array_utils.pytest"

[dependency-groups]
dev = [ "types-array-api", "types-docutils" ]
test = [
  "anndata",
  "fast-array-utils[full]",
  "jax",
  "jaxlib",
  "scikit-learn",
  { include-group = "dev" },
  { include-group = "test-min" },
]
doc = [
  "furo>=2024.8.6",
  "pytest>=8.4",
  "sphinx>=9.0.1",
  "sphinx-autofixture>=0.4.1",
]
test-min = [
  "coverage[toml]",
  "fast-array-utils[sparse,testing]", # include sparse for testing numba-less to_dense
  "pytest",
  "pytest-codspeed",
  "pytest-doctestplus",
  "pytest-xdist",
]
typecheck = [
  "array-api-compat!=1.15", # https://github.com/data-apis/array-api-compat/issues/436
  "mypy",
  "scipy-stubs",
  "sphinx",
]

[tool.hatch]
version.source = "vcs"
version.raw-options = { local_scheme = "no-local-version" }  # be able to publish dev version
metadata.hooks.docstring-description = {}
metadata.hooks.fancy-pypi-readme.content-type = "text/x-rst"
metadata.hooks.fancy-pypi-readme.fragments = [
  { path = "README.rst", start-after = ".. begin" },
]
build.targets.wheel.packages = [ "src/fast_array_utils", "src/testing" ]
envs.default.installer = "uv"
envs.docs.scripts.build = "sphinx-build -M html docs docs/_build"
envs.docs.scripts.clean = "git clean -fdX docs"
envs.docs.scripts.open = "python -m webbrowser -t docs/_build/html/index.html"
envs.docs.dependency-groups = [ "doc" ]
envs.hatch-check-code.dependencies = [ "prek" ]
envs.hatch-check-code.scripts.lint-check = "echo 'try `hatch check code --fix`'; false"
envs.hatch-check-code.scripts.lint-fix = "prek run -a --no-group=format --no-group=typecheck"
envs.hatch-check-fmt.dependencies = [ "prek" ]
envs.hatch-check-fmt.scripts.format-check = "echo 'try `hatch check fmt --fix`'; false"
envs.hatch-check-fmt.scripts.format-fix = "prek run -a --group=format --no-group=typecheck"
envs.hatch-check-types.scripts.check = [ "mypy" ]
envs.hatch-check-types.dependency-groups = [ "typecheck", "test" ]
envs.hatch-test.extra-dependencies = [ "ipycytoscape", "ipykernel" ]
envs.hatch-test.env-vars.CODSPEED_PROFILE_FOLDER = "test-data/codspeed"
envs.hatch-test.matrix = [
  { python = [ "3.14", "3.12" ], extras = [ "full", "min" ] },
  { python = [ "3.12" ], extras = [ "full" ], resolution = [ "lowest" ] },
]
envs.hatch-test.overrides.matrix.extras.dependency-groups = [
  { value = "test", if = [ "full" ] },
]
envs.hatch-test.overrides.matrix.resolution.dependencies = [
  { value = "numpy==2", if = [ "lowest" ] },
  { value = "dask==2023.6.1", if = [ "lowest" ] },
  { value = "scipy==1.13.0", if = [ "lowest" ] },
]
envs.hatch-test.default-args = []
envs.hatch-test.dependency-groups = [ "test-min" ]

[tool.uv]
override-dependencies = [ "sphinx>=9.0.1" ]

[tool.ruff]
line-length = 160
namespace-packages = [ "src/testing" ]
format.preview = true
format.docstring-code-format = true
lint.select = [ "ALL" ]
lint.ignore = [
  "A005",    # submodules never shadow builtins.
  "C408",    # dict() calls are nice
  "COM812",  # trailing commas handled by black
  "D203",    # prefer 0 to 1 blank line before class members
  "D213",    # prefer docstring summary on first line
  "FIX002",  # “TODO” comments
  "N812",    # lowercase imports are fine
  "PLC0415", # we rely heavily on non-top-level imports
  "PLR0913", # having many (kw)args is fine
  "Q",       # handled by formatter
  "S101",    # asserts are fine
  "TID252",  # relative imports are fine
]
# No __init__.py in docs
lint.per-file-ignores."docs/**/*.py" = [ "INP001" ]
# Shadows builtins like `sum`
lint.per-file-ignores."src/**/stats/*.py" = [ "A001", "A004" ]
lint.per-file-ignores."tests/**/*.py" = [
  "D100",    # tests need no module docstrings
  "D103",    # tests need no function docstrings
  "INP001",  # tests should not have __init__.py
  "PLR2004", # tests use magic values
  "S101",    # tests use `assert`
]
# Stubs don’t follow name conventions
lint.per-file-ignores."typings/**/*.pyi" = [ "A002", "F403", "F405", "N801" ]
lint.allowed-confusables = [ "×", "’" ]
lint.flake8-bugbear.extend-immutable-calls = [ "testing.fast_array_utils.Flags" ]
lint.flake8-copyright.notice-rgx = "SPDX-License-Identifier: MPL-2\\.0"
lint.flake8-type-checking.exempt-modules = []
lint.flake8-type-checking.strict = true
lint.isort.known-first-party = [ "fast_array_utils" ]
lint.isort.lines-after-imports = 2
lint.pydocstyle.convention = "numpy"
lint.future-annotations = true

[tool.mypy]
mypy_path = [ "$MYPY_CONFIG_FILE_DIR/typings", "$MYPY_CONFIG_FILE_DIR/src" ]
files = [ "." ]
explicit_package_bases = true
# https://github.com/dask/dask/issues/8853
implicit_reexport = true
strict = true

[tool.pyright]
stubPath = "./typings"
reportPrivateUsage = false

[tool.ty]
environment.extra-paths = [ "./typings" ]

[tool.pytest]
addopts = [
  "--import-mode=importlib",
  "--doctest-modules",
  "--doctest-plus",
  "--pyargs",
]
doctest_subpackage_requires = [
  "src/fast_array_utils/conv/scipy/* = scipy",
  "src/fast_array_utils/conv/scipy/_to_dense.py = numba",
  "src/fast_array_utils/numba/* = numba",
  "src/fast_array_utils/stats/* = numba",
  "src/fast_array_utils/_plugins/dask.py = dask",
  "src/fast_array_utils/_plugins/numba_sparse.py = numba;scipy",
]
markers = [
  "benchmark: marks tests as benchmark (to run with `--codspeed`)",
]
strict = true
testpaths = [ "./tests", "fast_array_utils" ]

[tool.coverage]
run.omit = [ "src/testing/*", "tests/*" ]
run.data_file = "test-data/.coverage"
report.exclude_also = [ "@(numba[.])?njit", "[.]{3}", "if TYPE_CHECKING:" ]
html.directory = "test-data/htmlcov"
xml.output = "test-data/coverage.xml"
